name: Ollama Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  ollama_review:
    name: Ollama Code Reviews
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Cache Ollama model
      uses: actions/cache@v2
      with:
        path: $HOME/.ollama/models
        key: ollama-model-${{ runner.os }}-${{ hashFiles('ollama.lock') }}
        restore-keys: ollama-model-${{ runner.os }}-
      
    - name: Install Ollama CLI
      run: |
        curl -fsSL https://ollama.com/install.sh | sh
        ollama serve &
        ollama pull llama3
        ollama show --modelfile llama3
      shell: bash

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v43

    - name: Review code
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
          file_content="$(cat $file)"
          prompt="Review this changeset. Provide suggestions for improvements, coding best practices, improve readability, and maintainability. Respond in markdown format $file_content"
          echo "$prompt" >> ollama_prompt.txt
          payload=$(jq -Rs '{ model: "llama3", stream: false, prompt: . }' ollama_prompt.txt)
          echo "$payload" >> ollama_payload.txt
          review=$(curl -H "Content-Type: text/xml" -v -s http://127.0.0.1:11434/api/generate --data-binary "@ollama_payload.txt" | jq -r '.response')
          comment="Ollama Code Review for \`$file\`: $review"
          echo "$comment" >> ollama_review.txt
          echo "$file_content"
        done

        gh pr comment ${{ github.event.pull_request.number }} --body "$(cat ollama_review.txt)"
      shell: bash
      
